import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/layouts/header";
import Footer from "@/components/custom/layouts/footer";

const sairaSans = Saira({
  variable: "--font-saira-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sairaSans.variable} ${sairaSans.className} antialiased`}
      >
        <div className="bg-[url(/images/grid.svg)] h-[600px] w-full absolute z-[60]" />
        <Header />
        {children}
        <Footer />
        <div />
      </body>
    </html>
  );
}
