// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Index": {
    "App_Name": "Parch Linux"
  },
  "head": {
    "title": "We have a <strong>ready-to-go</strong> OS!",
    "strong": "ready-to-go",
    "install": "Easy installation",
    "performance": "High-performance",
    "speed": "High-speed",
    "userUI": "User-friendly UI",
    "arch": "Powered by Arch",
    "desc": "ParchLinux is based on <arch>Arch Linux</arch> and offers a <userFriendly>user-friendly</userFriendly> experience with high <performance>performance</performance>.",
    "archWord": "Arch Linux",
    "userFriendlyWord": "user-friendly",
    "performanceWord": "performance"
  }
};
export default messages;