export const blogCopy = {
  fa: {
    eyebrow: "مجله پارچ",
    titleStart: "جایی برای",
    titleAccent: "لینوکس، متن‌باز و جامعه",
    titleEnd: "",
    intro:
      "خبرها، راهنماهای فنی، تجربه‌های تیم پارچ و نوشته‌هایی برای کسانی که دوست دارند سیستم‌شان را بهتر بشناسند.",
    latest: "تازه‌ترین نوشته‌ها",
    latestHint: "از انتشارهای جدید تا آموزش‌های عمیق و داستان‌های جامعه پارچ.",
    featured: "پیشنهاد سردبیر",
    all: "همه",
    search: "جستجو بین نوشته‌ها...",
    read: "مطالعه مقاله",
    minute: "دقیقه مطالعه",
    noResults: "چیزی با این جستجو پیدا نشد.",
    clear: "پاک کردن فیلترها",
    newsletterTitle: "بلاگ را با RSS دنبال کن",
    newsletterText: "نوشته‌های تازه را مستقیم داخل فیدخوان خودت بگیر؛ بدون ثبت‌نام، بدون ایمیل و بدون شلوغی.",
    rss: "دریافت RSS",
    archive: "آرشیو نوشته‌ها",
    articles: "نوشته",
    category: "دسته‌بندی",
    back: "بازگشت به بلاگ",
    toc: "در این مقاله",
    share: "اشتراک‌گذاری",
    related: "برای ادامه خواندن",
    updated: "به‌روزرسانی",
  },
  en: {
    eyebrow: "Parch Journal",
    titleStart: "Notes on",
    titleAccent: "Linux, open source & community",
    titleEnd: "",
    intro:
      "Release stories, practical guides, engineering notes and community writing from the people building Parch GNU/Linux.",
    latest: "Latest stories",
    latestHint: "From release notes to deep technical guides and stories from the Parch community.",
    featured: "Editor’s pick",
    all: "All",
    search: "Search stories...",
    read: "Read article",
    minute: "min read",
    noResults: "No stories match that search.",
    clear: "Clear filters",
    newsletterTitle: "Follow the journal with RSS",
    newsletterText: "Get new stories directly in your feed reader — no account, no email and no inbox noise.",
    rss: "Open RSS feed",
    archive: "Story archive",
    articles: "articles",
    category: "category",
    back: "Back to blog",
    toc: "On this page",
    share: "Share",
    related: "Keep reading",
    updated: "Updated",
  },
} as const;

export function getBlogCopy(locale: string) {
  return locale === "fa" ? blogCopy.fa : blogCopy.en;
}
